-- SUB QUERY : QUERY INSIDE ANOTHER QUERY
SELECT MAX(SALARY)
FROM EMPLOYEES;

-- FIND OUT THE MAX SALARY FROM EMPLOYEE TABLE
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY = 24000;

--WE HARD CODED THE VALUE OF 24000 WE GOT FROM FIRST QUERY INTO SECOND QUERY
--NOW JUST LIKE FUNCTION CALL WE CAN USE THIS QUERY
--AS A BLOCK OF QUERY THAT GENERATE MAX SALARY ANYTIME
--SO EVEN IF MAX SALARY CHANGE AT SOME POINT WE WOULD GET CORRECT RESULT

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY)
                FROM EMPLOYEES);


--FIND OUT THE NAME OF THE EMPLOYEE THAT MAKES THE LEAST SALARY

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);

--FIND OUT THE NAME OF THE EMPLOYEE THAT MAKES MORE THAN AVERAGE SALARY
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

--DISPLAY ALL EMPLOYEES IF SALARY IS NOT 24000 - AKA SECOND MAX SALARY
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY <> (SELECT MAX(SALARY) FROM EMPLOYEES);

--3RD MAX SALARY -- ALL SALARIES LESS THAN THE SECOND MAX
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY <> (SELECT MAX(SALARY) FROM EMPLOYEES));

--FIND OUT THE FIRST_NAME OF EMPLOYEES WHO WORKS IN EXECUTIVE DEPARTMENT
-- FIND OUT THE DEPARTMENT ID OF EXECUTIVE
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'Executive';

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

--NOW COMBINE THEM
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS
                         WHERE DEPARTMENT_NAME = 'Executive');

-- FIND OUT THE FIRST_NAME OF EMPLOYEES
-- WHO WORKS IN Executive AND Administrative Department


-- FIND OUT THE DEPARTMENT_ID OF  Executive
-- AND Administration Department
SELECT DEPARTMENT_ID FROM DEPARTMENTS
WHERE DEPARTMENT_NAME IN ('Executive', 'Administration')
;
--- FIND OUT THE FIRST_NAME OF EMPLOYEES
-- WHO WORKS IN department_id 90 and 10
SELECT FIRST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10,90) ;

--COMBINE THE RESULT

SELECT FIRST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS
                        WHERE DEPARTMENT_NAME IN ('Executive', 'Administration') );

---RESULT OF SUB QUERY CAN ALSO BE USED AS ENTIRE TABLE
--FOR EXAMPLE SELECT * FROM (SUB QUERY GOES HERE)

SELECT FIRST_NAME, LAST_NAME, FIRST_NAME || LAST_NAME AS FULL_NAME
FROM EMPLOYEES
--WHERE FULL_NAME = 'EllenAbel'; WE CAN NOT USE ALIAS IN A CONDITION
;

SELECT *
FROM (SELECT FIRST_NAME, FIRST_NAME || LAST_NAME AS FULL_NAME
      FROM EMPLOYEES)
WHERE FULL_NAME = 'EllenAbel';

--FIND OUT THE EMPLOYEE COUNT OF THE DEPARTMENT WITH MOST EMPLOYEE
SELECT DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

--FIND OUT THE EMPLOYEE COUNT OF THE DEPARTMENT WITH MOST EMPLOYEE
SELECT MAX(EMPLOYEE_COUNT)
FROM (SELECT DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT
      FROM EMPLOYEES
      GROUP BY DEPARTMENT_ID);

--FIND OUT DEPARTMENT_ID OF THE DEPARTMENT WITH MOST EMPLOYEE
SELECT DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50
GROUP BY DEPARTMENT_ID;


--DENSE_RANK() OVER (ORDER BY SALARY)
SELECT FIRST_NAME, SALARY,
       DENSE_RANK() over (ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES;

--NOW WE CAN SEE THIS WHOLE RESULT OF ABOVE QUERY AS A TABLE
--SELECT * FROM EMP_SALARY_RANK WHERE SALARY_RANK = 4;
SELECT *
FROM (SELECT FIRST_NAME, SALARY,
             DENSE_RANK() over (ORDER BY SALARY DESC) AS SALARY_RANK
      FROM EMPLOYEES)
      WHERE SALARY_RANK = 40;

--RANK
SELECT *
FROM (SELECT FIRST_NAME, SALARY,
             DENSE_RANK() over (ORDER BY SALARY DESC) AS SALARY_RANK
             --,RANK() over (ORDER BY SALARY DESC) JUST FOR AN FYI
      FROM EMPLOYEES)
WHERE SALARY_RANK = 3;


/*
Select * FROM (
                  select  first_name as Given_Name from employees)
Where Given_Name = 'Steven' ;
#
Hold that thought 💭 until better example on why you might wanna try.

 */



