SELECT HIRE_DATE FROM EMPLOYEES;

-- EXTRACT FUNCTION IS A SINGLE ROW FUNCTION
-- THAT CAN EXTRACT ANY PART OF DATE TIME COLUMN
-- LIKE YEAR , MONTH , DAY , HOUR , MINUTE, SECOND

--EXTRACT THE YEAR FROM THE HIRE_DAT
SELECT HIRE_DATE , EXTRACT(YEAR  FROM HIRE_DATE) AS HIRED_YEAR
FROM EMPLOYEES
ORDER BY HIRE_DATE;

-- SELECT THE MONTH FROM THE HIRE_DATE
SELECT HIRE_DATE , EXTRACT(MONTH FROM HIRE_DATE) AS HIRED_MONTH
FROM EMPLOYEES;

-- FIND OUT ALL EMPLOYEES HIRED IN YEAR 2008
SELECT FIRST_NAME, HIRE_DATE, EXTRACT(YEAR FROM HIRE_DATE)
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2008;

--FIND OUT ALL EMPLOYEES HIRED IN YEAR 2001 UNTIL 2003
SELECT FIRST_NAME, HIRE_DATE, EXTRACT(YEAR FROM HIRE_DATE)
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) BETWEEN 2001 AND 2003;

--FIND OUT HOW MANY PEOPLE ARE HIRED IN EACH YEAR
SELECT EXTRACT(YEAR FROM HIRE_DATE) AS HIRED_YEAR,
       COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY EXTRACT(YEAR FROM HIRE_DATE)
HAVING COUNT(*) > 15 --IF WE WANT TO ADD A CONDITION AFTER GROUP BY
ORDER BY 1; --ORDER BY 1ST COLUMN IN SELECT STATEMENT
