/*
 1.1 Display Employee_ID , FIRST_NAME ,  LAST_NAME
        for Employee_ID , 100 , 110 , 120
 */
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 100
   OR EMPLOYEE_ID = 110
   OR EMPLOYEE_ID = 120;

/*
 1.1 Display Employee_ID , FIRST_NAME ,  LAST_NAME
        for Employee_ID 100 to 115  excluding 110
 */
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID BETWEEN 100 AND 115
  AND EMPLOYEE_ID != 110;

-- 1.2 Display Employee with No Manager_ID

SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

-- 1.3 Display Employee with No DEPARTMENT_ID
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

-- 1.4 Display All Employees from Department 40 to 70
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 40 AND 70;

/*
 1.5 Display All Employees with JOB_ID ST_CLERK
 AND SALARY more than 3000 ORDER the result by FIRST_NAME
 */
SELECT *
FROM EMPLOYEES
WHERE JOB_ID = 'ST_CLERK'
  AND SALARY > 3000;

/*
 1.6 Display Employee FIRST_NAME , SALARY ,
 COMMISSION_VALUE  (SALARY*COMMISSION_PCT)
    if the Employee has COMMISSION_PCT value
    Order the result in COMMISSION_VALUE high to low
 (can not use alias, you can use index 3)
 */
SELECT FIRST_NAME,
       SALARY,
       (SALARY * COMMISSION_PCT) AS COMMISSION_VALUE
FROM EMPLOYEES
WHERE COMMISSION_PCT != 0
ORDER BY COMMISSION_PCT;

-- 1.7 Display UNIQUE MANAGER_ID
SELECT DISTINCT MANAGER_ID
FROM EMPLOYEES;

-- 1.8 Display UNIQUE DEPARTMENT_ID
SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES;

-- 1.9 Display UNIQUE JOB_ID
SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

-- 1.10 Display All Employee Full Name that report
-- to Manager_ID 100
SELECT FIRST_NAME || ' ' || LAST_NAME, MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID = 100;


-- FROM Departments Table
-- 1.11 Display All Department that HAS MANAGER_ID  AND AT LOCATION_ID 1700
SELECT *
FROM DEPARTMENTS
WHERE MANAGER_ID != 0
  AND LOCATION_ID = 1700;

-- 1.12 Display DEPARTMENT_NAME of DEPARTMENT_ID 10, 20 , 130
SELECT DEPARTMENT_NAME, DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 10
   OR DEPARTMENT_ID = 20
   OR DEPARTMENT_ID = 130;

-- 1.12 Display DEPARTMENT_NAME of DEPARTMENT_ID NOT BETWEEN 30 - 100
SELECT DEPARTMENT_NAME, DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_ID NOT BETWEEN 30 AND 100;

-- 1.13 Display Unique LOCATION_ID
SELECT DISTINCT LOCATION_ID
FROM DEPARTMENTS;

--From location
-- Count how many locations we have
SELECT COUNT(*)
FROM LOCATIONS;

-- 2.4 Display All Departments with DEPARTMENT_NAME Contains IT
--  exclude the exact match department name IT
SELECT * FROM DEPARTMENTS
WHERE DEPARTMENT_NAME LIKE 'IT%';

--3.4 Display the Employee Count for EACH FIRST_NAME (yeah and observe what you got)
--Filter the grouped result to only display if the count is more than 1
SELECT FIRST_NAME, COUNT(*)
FROM EMPLOYEES
GROUP BY FIRST_NAME
HAVING COUNT(*) > 1;